name: Docker Swarm Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout codes
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t resume_node:latest .
      
      - name: Log in to Docker Hub
        run: docker login -u $DOCKERHUB_USERNAME -p ${{ secrets.DOCKERHUB_PASSWORD }}


      - name: Push Docker images
        run: docker push resume_node:latest

      # - name: Deploy to Docker Swarm
      #   run: |
      #     ssh user@your-swarm-manager 'docker service update --image resume_node:latest your-service-name'
